micronaut:
  server:
    port: 50002
  router:
    static-resources:
      swagger:
        paths: 'classpath:META-INF/swagger'
        mapping: '/swagger/**'
      rapidoc:
        paths: 'classpath:META-INF/swagger/views/rapidoc'
        mapping: '/rapidoc/**'

internal:
  urls:
    todo-service: http://localhost:50001
